### ISSUE TITLE
adding clear background

### ISSUE THREAD

**Issue by fillytown** [AdilSoomro/ASTextField#2]
Hello.  I love the look and feel of the custom UITextField that you have created.   I am working to implement it into a project that I am working on, but I cannot get the background of the UITextField to be clear.  It remains visible (white in the image).   

The clearColor method is implemented, but it remains white.  Is there a way to fix this?

Photo attached.

I am using iOS 9 Xcode 7.1

![simulator screen shot nov 16 2015 2 22 52 pm](https://cloud.githubusercontent.com/assets/15878610/11195144/8d936ab6-8c6d-11e5-983f-8eb38eb580ad.png)

**Comment by AdilSoomro** [comment]
It has been fixed in latest commit.
